### ISSUE TITLE
'Votes' function fails to aggregate votes when regional_aggregation is specified

### ISSUE THREAD

**Issue by JonnyPhillips** [Cepesp-Fgv/cepesp-r#11]
Eg. votes(year=2014, position="President", regional_aggregation="Brazil") fails to return the 17 rows it should - it returns about 11,000 rows, apparently for each Micro_regiao. This appears to be due to the specification of the columns_list() which introduces columns for NOME_MICRO, NOME_MESO etc. and somehow that seems to prevent the aggregation of votes to the level of 'Brazil'. 
When I access the underlying code and specify columns_list=list() the problem is fixed and the aggregation is correct (17 rows). So this seems to be a problem with the default specification of the columns for the function.

**Comment by luizgabriel** [comment]
The argument "position" is a numerical value.
1 - President
3 - Governor
5 - Senator
6 - Federal Deputy
7 - State Representative
8 - Deputy District
11 - Mayor
13 - Councilman

The same way goes to regional aggregation:
0 - Brazil
2 - Federal Unit
6 - County
7 - County-Zone
8 - Zone
1 - Macro Region
4 - Meso Region
5 - Micro Region

The correct way of doing this request is:
votes(year=2014, position=1, regional_aggregation=0)

**Comment by luizgabriel** [comment]
Fixed.
