### ISSUE TITLE
NOME_UF contains wrong data

### ISSUE THREAD

**Issue by JonnyPhillips** [Cepesp-Fgv/cepesp-r#12]
Including NOME_UF in the colums_list request returns a column of unexpected data and also multiplies the number of rows returned indicating an error in merging. NOME_UF includes some real state names (Acre, Alagoas etc.) but also four letter all caps codes like: ANGO, ARAB, ARGT, AUST, BELG, BOLI....

**Comment by atrfisch** [comment]
Johnathan,
Brazilians who live abroad can vote in presidential elections. So the TSE has a special UF code (unidade da federação) for these voters, which is called ZZ. The name of UF is the name an abbreviation of the name of the country where the vote was cast. For example: ANGO is Angloa, ARAB is Saudi Arabia, ARGT is Argentina.
