### ISSUE TITLE
Inlusion of Num_zona in default columns_list returns no data

### ISSUE THREAD

**Issue by JonnyPhillips** [Cepesp-Fgv/cepesp-r#13]
Running a basic test with the beta cepespdata function, eg. cepespdata(year=2014, position="President", regional_aggregation="Brazil", political_aggregation="Candidate"), returns no data. This occurs due to the inclusion of NUM_ZONA in the columns_list for regional_aggregation=0. In fact, it looks like all the columns for regional_aggregation=0 needs to be checked as there's no reason they should include disaggregated columns such as NOME_MESO, NOME_MICRO, NUM_ZONA etc.

**Comment by luizgabriel** [comment]
Fixed.
