### ISSUE TITLE
cepespdata function missing data

### ISSUE THREAD

**Issue by paeselhz** [Cepesp-Fgv/cepesp-r#15]
While working with the cepespdata function, I've realized that there are missing lots of Parties, also lots of Candidates. i.e: For the state of São Paulo, when extracting data about the State Deputies, Parties and Candidates are missing.

Thanks,
Luis Paese

**Comment by voronoysOLD** [comment]
Has this been fixed? I have the same problem, when I try consult the candidates the data is missing, mainly when the data is from 1998 ~ 2004.

**Comment by Cepesp-Fgv** [comment]
We're are currently developing a new implementation for the data merge algorithm so we can resolve theses problems with missing data. See #18 for any further discussion.
