### ISSUE TITLE
Section - regional aggregation

### ISSUE THREAD

**Issue by voronoysOLD** [Cepesp-Fgv/cepesp-r#16]
It was asked in the "Oficina" if it is possible provide the data from electoral section. More than it, do you have the data about its locations(lat/long)? So, I would like to use the data come from electoral section as many as possible. 

Thanks in advance.

**Comment by Cepesp-Fgv** [comment]
@voronoys, we've implemented a new regional aggregation (9 - Electoral Section) that comes with the electoral section data, but it's stills not returning any lat/lng coordinates.

**Comment by voronoysOLD** [comment]
It's not working. I code:

teste <- votes(year=2016,
           position="Mayor",
           regional_aggregation="Electoral Section")

it returns: Parsed with column specification:
cols(
  COD_MUN_TSE = col_character()
)

And a Data.Frame empty.

I tried code:

teste <- votes(year=2014,
           position="President",
           regional_aggregation="Electoral Section")

it returns a error: 
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  first five rows are empty: giving up
