### ISSUE TITLE
Cepespdata function - Consult Districtal Deputy Problem

### ISSUE THREAD

**Issue by voronoysOLD** [Cepesp-Fgv/cepesp-r#17]
Problem: I can't request the districtal deputy, it returns me the president position.

**Comment by Cepesp-Fgv** [comment]
@voronoys, can you please provide us an example of the request that returned this kind of result? We're were not able to simulate this error, so we need more information to investigate.

**Comment by voronoysOLD** [comment]
code:
teste <- cepespdata(year=2014,
               position="Deputado Distrital",
               regional_aggregation="Estado")

It returns a data frame with votes of the president candidates for each state. I need the Districtal Deputy, because its equivalent to State Deputy  in  the state "Distrito Federal". If I trie to do this in the cepesp.io, I can consult the candidates.

**Comment by Cepesp-Fgv** [comment]
Fixed! There was a misspelling error on the conversion of "Deputado Distrital" to the respective code of this position.
