### ISSUE TITLE
Cepespdata function improvement

### ISSUE THREAD

**Issue by voronoysOLD** [Cepesp-Fgv/cepesp-r#18]
Can this function return the information about the candidates? Because the function cepespdata it's not working very well and it's better get more information about candidates to make the analysis.

Merge data on function candidate and votes has a high cost, computationally.

**Comment by Cepesp-Fgv** [comment]
We're currently developing this feature and it will be available as soon as possible.

**Comment by Cepesp-Fgv** [comment]
Update: There is now a **votes_x_candidates()** function calls both candidades and votes functions and join then together.
