### ISSUE TITLE
Candidates function - error 2000 election

### ISSUE THREAD

**Issue by voronoysOLD** [Cepesp-Fgv/cepesp-r#19]
When I try consult data about candidates like this:

teste <- candidates(year = 2000,
                    position = "Vereador")

return this error:

Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  first five rows are empty: giving up

**Comment by voronoysOLD** [comment]
Maybe the problem is in the data from this election.

I tried to code:
teste <- cepespdata(year = 2000,
                    regional_aggregation = 'Municipio',
                    position = 'Vereador')
it returns just 16414 rows. A lot data is missing and a warning message:

In rbind(names(probs), probs_f) :
  number of columns of result is not a multiple of vector length (arg 1)

**Comment by Cepesp-Fgv** [comment]
This error is not related to the R api itself. We've found some invalid characters on the output files which caused this strange error on the candidates function and it's now fixed.

**Comment by Cepesp-Fgv** [comment]
```r
get_candidates(year = 2000, position = "Vereador")
```
It's now working properly.
