### ISSUE TITLE
Electoral Section aggregation not returning any data

### ISSUE THREAD

**Issue by JonnyPhillips** [Cepesp-Fgv/cepesp-r#22]
Any request with regional_aggregation="Electoral Section" returns
Parsed with column specification:
cols(
  .default = col_character()
)
And zero rows of data. Eg. 
votes(year=2006,position="President", regional_aggregation="Electoral Section")

**Comment by Cepesp-Fgv** [comment]
As described in our documentation, every request to regional_aggregation="Electoral Section" needs a state="STATE" filter to be passed.

**Comment by Cepesp-Fgv** [comment]
votes(year=2006,position="President", regional_aggregation="Electoral Section", **state="AC"**) works good.

**Comment by JonnyPhillips** [comment]
Thanks, I hadn't realized that, apologies. But the response from your proposed code is still empty for me. (0 rows). The same is true for any year. (I think I have the latest cepespR version). The message returned is: 
votes(year=2006,position="President", regional_aggregation="Electoral Section", state="AC")
Parsed with column specification:
cols(
  .default = col_character()
)
See spec(...) for full column specifications.

From working through the function the request it's sending is:
"http://cepesp.io/api/consulta/votos?anos=2014&agregacao_regional=9&agregacao_politica=0&cargo=1&selected_columns%5B%5D=ANO_ELEICAO&selected_columns%5B%5D=SIGLA_UE&selected_columns%5B%5D=NUM_TURNO&selected_columns%5B%5D=DESCRICAO_ELEICAO&selected_columns%5B%5D=CODIGO_CARGO&selected_columns%5B%5D=DESCRICAO_CARGO&selected_columns%5B%5D=NUMERO_CANDIDATO&selected_columns%5B%5D=QTDE_VOTOS&selected_columns%5B%5D=CODIGO_MACRO&selected_columns%5B%5D=NOME_MACRO&selected_columns%5B%5D=UF&selected_columns%5B%5D=NOME_UF&selected_columns%5B%5D=CODIGO_MESO&selected_columns%5B%5D=NOME_MESO&selected_columns%5B%5D=CODIGO_MICRO&selected_columns%5B%5D=NOME_MICRO&selected_columns%5B%5D=COD_MUN_TSE&selected_columns%5B%5D=COD_MUN_IBGE&selected_columns%5B%5D=NOME_MUNICIPIO&selected_columns%5B%5D=NUM_ZONA&selected_columns%5B%5D=NUM_SECAO&columns%5B0%5D%5Bname%5D=UF&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=AC"

**Comment by Cepesp-Fgv** [comment]
On "Electoral Section" queries, the Rest API param "uf_filter" is mandatory.
Ex: http://cepesp.io/api/consulta/votos?anos=2014&agregacao_regional=9&agregacao_politica=2&cargo=1&uf_filter=CE

For more info: https://github.com/Cepesp-Fgv/cepesp-rest/blob/master/EleicoesPorCargo.md#par%C3%A2metros-da-url

**Comment by Cepesp-Fgv** [comment]
On "Electoral Section" queries, the Rest API param "uf_filter" is mandatory.

For more info: https://github.com/Cepesp-Fgv/cepesp-rest/blob/master/EleicoesPorCargo.md#par%C3%A2metros-da-url
