### ISSUE TITLE
Faltando voto de legenda usando o código cepespdata

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#27]
Oi pessoal,
Notei uma inconsistência no código entre usar "get_votes" e "cepespdata". Ao pedir os candidatos pra deputado federal por estado, a função get_votes me traz os votos de legenda, enquanto o cepespdata não. Isto é, com o primeiro código abaixo, o df contém observações do partido com NUMERO_CANDIDATO=={10, 13, 25, 45, 50}, enquanto o segundo código apenas apresenta os candidatos NUMERO_CANDIDATO=>10000 .

fed_deputy_2010<-as.data.frame(get_votes(year=2010, position="Federal Deputy", regional_aggregation="State"))

fed_deputy_2010<-as.data.frame(cepespdata(year=2010, position="Federal Deputy", regional_aggregation="State",))

**Comment by Cepesp-Fgv** [comment]
```r
get_elections(year=2010, position="Federal Deputy", regional_aggregation="State")  get_votes(year=2010, position="Federal Deputy", regional_aggregation="State")
```
Agora retornam votos legenda corretamente.
