### ISSUE TITLE
Missing candidates in "get_election(2014, "Federal Deputy")

### ISSUE THREAD

**Issue by Gabiscampos** [Cepesp-Fgv/cepesp-r#29]
Ao usar a função get_election(2014, "Deputado Federal") retorna apenas 458 eleitos, quando deveria ser 513. 

Estão faltando candidatos na base de dados (exemplo, candidato Tiririca | NUM_TITULO_ELEITORAL = 12504970710).

Para outros anos valores estão normais.

**Comment by Gabiscampos** [comment]
Este problema se dá no cepesp.io quando se adiciona colunas relativo a base de coligações.
 
Se você fizer a consulta só com os campos default tem 6,873 entradas. Quando se adiciona qualquer uma das  colunas "TIPO_LEGENDA", "SIGLA_COLIGACAO" ou "COMPOSICAO_COLIGACAO",  cai para 5,356 entradas. 

Acredito que esta perda de dados deve estar ligado a junção das bases de coligação com votos e candidatos.

**Comment by Cepesp-Fgv** [comment]
```r
 get_elections(2014, "Deputado Federal")
```
Ano 2014 agora retorna 513 eleitos corretamente.
