### ISSUE TITLE
Missing observation in get_elections

### ISSUE THREAD

**Issue by Gabiscampos** [Cepesp-Fgv/cepesp-r#31]
Olá, 

Estou fazendo a consulta: 
pref_2000<- get_elections(year=2000, position="Prefeito", regional_aggregation="Brasil", political_aggregation="Candidate")

E está me retornando 181 observações. Quando faço a mesma consulta no cepesp.io, me retornam 9,919 observações. Pode verificar o que acontece?

Abs, Gabi

**Comment by Cepesp-Fgv** [comment]
```r 
get_elections(year=2000, position="Prefeito", regional_aggregation="Brasil", political_aggregation="Candidate")
```
esta consulta e a feita pelo cepesp.io retornam agora exatos 13604 em ambos.
