### ISSUE TITLE
Duplicated Votes for President in Consolidated/Beta Data

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#32]
O total de votos para os candidatos por município estão dobrados quando usando a base de dados consolidada-Beta.
A base apenas com votos está correta, mas a Beta não. Não sei esse problema é só para os dados por município ou se estão (acredito que devem estar) afetando as outras agregações também.

**Comment by Cepesp-Fgv** [comment]
Consultas no “beta” (get_elections) não apresentam mais duplicações nos votos.
