### ISSUE TITLE
função CepespR

### ISSUE THREAD

**Issue by Leonardo-Bueno** [Cepesp-Fgv/cepesp-r#33]
Para a versão mais recente do R. Recebo a seguinte mensagem:
Warning in install.packages :
  package ‘CepespR’ is not available (for R version 3.5.1)

**Comment by RCCSilva** [comment]
@Leonardo-Bueno, acredito que você tenha utilizado a função `install.packages("cepespR")`. Contudo, você precisa utilizar os seguintes comandos:

```r
if (!require("devtools")) install.packages("devtools")
devtools::install_github("Cepesp-Fgv/cepesp-r")
library(cepespR)
```

**Comment by Leonardo-Bueno** [comment]
Ah, é isso mesmo! Agora funcionou! Obrigado Rafa!
