### ISSUE TITLE
Option columns_list not working

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#34]
A função get_candidates não seleciona as variáveis da base de dados com a opção columns_list.

```r
library(cepespR)
columns <-list("SIGLA_UF", "SIGLA_PARTIDO")
foo<-get_candidates(2014, "State Deputy", columns_list=columns)>
```
Aparentemente, a opção funciona com o get_votes.

**Comment by Cepesp-Fgv** [comment]
Opção columns_list agora funciona corretamente.
