### ISSUE TITLE
Problema com a função get_elections

### ISSUE THREAD

**Issue by Leonardo-Bueno** [Cepesp-Fgv/cepesp-r#36]
Estou puxando dados usando a função get_election. Independente do regional_aggregation que escolho os dados vem sempre ao nível do município. Usei os seguintes códigos:

consolidado_df <- cepespR::get_elections("1998", 6, regional_aggregation = "Estado", political_aggregation = "Candidato")
consolidado_df_2 <- cepespR::get_elections("1998", 6, regional_aggregation = "Brasil", political_aggregation = "Candidato")

Nos dois casos veio o mesmo número de observações e ao nível do município, o que está errado.

**Comment by Leonardo-Bueno** [comment]
O problema parece ser nos dados de 1998 a 2006. 2010 e 2014 não dá erro.

**Comment by Cepesp-Fgv** [comment]
Agregações Estado e Brasil do ano 1998 agora retornam quantidade de observações distintas.
