### ISSUE TITLE
Partidos na lista de votos

### ISSUE THREAD

**Issue by marcofaga** [Cepesp-Fgv/cepesp-r#37]
Olá. Acho que a função votos poderia retornar também uma coluna indicando o partido do candidato. O nome do candidato também seria interessante. Também acho que poderia estar indicado a representação dos votos 90, 95 e 96.

**Comment by marcofaga** [comment]
PS. Na agregação Municipal.

**Comment by marcofaga** [comment]
> Olá. Acho que a função votos poderia retornar também uma coluna indicando o partido do candidato. O nome do candidato também seria interessante. Também acho que poderia estar indicado a representação dos votos 90, 95 e 96.

Ps. Na agregação Municipal.

**Comment by Gabiscampos** [comment]
Olá Marco, obrigada pela sugestão! 
Como política de tratamento de dados, decidimos não alterar e nem incluir novas colunas nas bases originais do TSE (votos, coligações e candidatos). Para olhar a votação em conjunto com informação dos candidatos é possível utilizar o banco de eleições e selecionar apenas colunas de interesse. 

Quanto aos votos de brancos e nulos (95 e 96) estamos trabalhando com um "Leia-me" para deixar mais fácil o entendimento e vamos considerar a alteração para o banco de eleições. 

Caso tenha outras sugestões, por favor compartilhe.

**Comment by marcofaga** [comment]
Mas no caso, não existem dados agregados por município no repositório de dados do TSE. Ou seja, já é um dado tratado, não é?
