### ISSUE TITLE
Impossível baixar banco de vereadores

### ISSUE THREAD

**Issue by Gabiscampos** [Cepesp-Fgv/cepesp-r#38]
Ao rodar:
df<-get_elections(2016, "Vereador")

retorna um banco com 0 observações. Outros bancos funcionam normal.

Problema é recorrente para todos os anos.

**Comment by elianalins** [comment]
A requisição

`x <- cepespR::get_elections(year=2012, position="Vereador", regional_aggregation="Votação Seção", political_aggregation="Candidate")`

não funciona. Testamos com parâmetros em inglês e em português.
