### ISSUE TITLE
Consulta de eleições de Governador não estão funcionando

### ISSUE THREAD

**Issue by Gabiscampos** [Cepesp-Fgv/cepesp-r#39]
A consulta a informação de eleições para governador não está funcionando nem no cepesp.io, nem na API:

http://cepesp.io/consulta/tse?cargo=3&agregacao_regional=1&agregacao_politica=2&anos%5B%5D=2010&uf_filter=&mun_filter=

df<-get_elections(2014, "Governador")

Pode verificar este ponto?

**Comment by Cepesp-Fgv** [comment]
```r 
df <- get_elections(2014, "Governador")
```
Agora funciona corretamente.
