### ISSUE TITLE
Missing COMPOSICAO_LEGENDA in 1998, 2006 and 2010 candidate databases

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#40]
df<-get_candidates(2006, "Federal Deputy")
table(df$COMPOSICAO_LEGENDA)
returns all #NE#

The same applies to 1998 and 2010, but not to 2002 and 2014.

**Comment by Cepesp-Fgv** [comment]
The column COMPOSICAO_LEGENDA is now correctly available on all get_candidates() queries of 2006.
