### ISSUE TITLE
Missing 2000 and 2004 Local Election Data from Tocantins

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#41]
Erro ao requisitar:
df<-get_votes(2000, "Prefeito", state="TO")
df<-get_votes(2004, "Vereador", state="TO")

mas funciona para os outros estados, e.g.,
df<-get_votes(2000, "Prefeito", state="SC")
df<-get_votes(2004, "Vereador", state="SP")

**Comment by Cepesp-Fgv** [comment]
O arquivo fonte  ([http://agencia.tse.jus.br/estatistica/sead/odsele/votacao_secao/votacao_secao_2000_TO.zip](http://agencia.tse.jus.br/estatistica/sead/odsele/votacao_secao/votacao_secao_2000_TO.zip)) que utilizamos para processar os votos está vazio. 

Assim que o TSE disponibilizar os dados, nós atualizaremos.

-----
Sobre o ano 2004, os dados agora estão disponíveis.
