### ISSUE TITLE
Empty "DF", "Deputado Distrital" datasets

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#42]
Todas os resultados de eleição para Deputado Distrital no DF estão vindo vazios.
Por exemplo,
df<-get_votes(1998, "Deputado Distrital", state=“DF”)
nrow(df)

**Comment by Cepesp-Fgv** [comment]
```r
df <- get_votes(1998, "Deputado Distrital", state=“DF”)
nrow(df)
```
Agora retorna 648 resultados.
