### ISSUE TITLE
2014 votes missing for president

### ISSUE THREAD

**Issue by Gabiscampos** [Cepesp-Fgv/cepesp-r#43]
Votos para presidente não estão retornando as eleições de 2014 nem na consulta de votos (http://cepesp.io/consulta/votos?cargo=1&agregacao_regional=2&anos%5B%5D=2018&anos%5B%5D=2014&anos%5B%5D=2010&anos%5B%5D=2006&anos%5B%5D=2002&anos%5B%5D=1998&uf_filter=&brancos=1&nulos=1)

nem na consulta de eleições (http://cepesp.io/consulta/tse?cargo=1&agregacao_regional=2&agregacao_politica=2&anos%5B%5D=2014&uf_filter=&mun_filter=)

Para outras eleições retorna normal

**Comment by Cepesp-Fgv** [comment]
@Gabiscampos, o problema foi resolvido.
