### ISSUE TITLE
Problema na consulta de Vereador Consolidado

### ISSUE THREAD

**Issue by Gabiscampos** [Cepesp-Fgv/cepesp-r#45]
x<-get_elections(2012, "Vereador", political_aggregation = "Consolidado")

Error in query_get_result(query_id) : 
  An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.

**Comment by Cepesp-Fgv** [comment]
O problema foi resolvido.

**Comment by Gabiscampos** [comment]
Oi, a consulta está com problema novamente: 
> votos_validos<-cepespR::get_elections(year="2008", 
                                       position = "Vereador", 
                                       political_aggregation = "Consolidado")
status: RUNNING, elapsed: 1s
status: FAILED, elapsed: 16s
Error in query(build_params(table = "tse", year = year, uf = state, regional_aggregation = regional_aggregation,  : 
  The query has failed. Please, check if your parameters are valid.

Para 2012 está funcionando, mas 2008 e 2016 não
