### ISSUE TITLE
Seta da consulta no CepespData.io

### ISSUE THREAD

**Issue by lins-morandi** [Cepesp-Fgv/cepesp-r#46]
Consulta de prefeitos p/ municípios do CE: a seta p/ visualização no site do cepespdata não funciona; ao avançar com a seta p/ a página seguinte, aparecem os mesmos prefeitos que constavam na página inicial. Ao baixar o arquivo em CSV, Ele retorna normalmente todos os prefeitos do Ceará.

**Comment by Cepesp-Fgv** [comment]
Os problemas relacionados a paginação foram corrigidos.
