### ISSUE TITLE
Problems with the 2000 candidates database

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#53]
Existem alguns problemas com este banco- get_candidates(2000, "Mayor"):
1- Candidatos repetidos
2- As linhas duplicadas indicam que o candidato foi ao segundo turno (NUM_TURNO), quando nao existe segundo turno nestas eleicoes
3- Nestes casos, a variavel DESC_SIT_TOT_TURNO tambem indica #NULO#

Acredito que limpando estas linhas duplicadas, o problema inteiro deve ser solucionado. Mas cuidado pra nao eliminar as linhas onde realmente houve segundo turno.

**Comment by lins-morandi** [comment]
Atualizamos o banco de dados de 2000.  Fiz a verificação com o Título de eleitor e Nº do turno simultaneamente. Não houve nenhum duplicated.
