### ISSUE TITLE
Error in API request for consolidated municipal data

### ISSUE THREAD

**Issue by JonnyPhillips** [Cepesp-Fgv/cepesp-r#55]
The following request generates the error:
"Error in query_get_result(query_id, dev) : 
  An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist."

get_elections(year=2014, position=5, state="AC",regional_aggregation = "Municipality", political_aggregation="Consolidated")

The similar query for the state level of aggregation works without any problem:

get_elections(year=2014, position=5, state="AC",regional_aggregation = "State", political_aggregation="Consolidated")

**Comment by Cepesp-Fgv** [comment]
Both queries are now running with no problems.
