### ISSUE TITLE
Coluna SEQUENCIAL_CANDIDATO não disponível no banco

### ISSUE THREAD

**Issue by Gabiscampos** [Cepesp-Fgv/cepesp-r#56]
Para fazer o join com o banco de bens de candidatos é preciso da coluna de SEQUENCIAL_CANDIDATO, disponível no banco original do TSE. 

Adicionar novamente a coluna no banco de candidatos para que seja possível fazer o join.

**Comment by Cepesp-Fgv** [comment]
Coluna adicionada.
