### ISSUE TITLE
Option "state" in get_elections not working

### ISSUE THREAD

**Issue by guirusso** [Cepesp-Fgv/cepesp-r#58]
Quando faço a requisição de get_elections para um estado (e.g. Acre), o filtro como option não funciona:
`tab<-get_elections(2004, "Councillor", columns_list = c("NUM_TITULO_ELEITORAL_CANDIDATO", "NOME_UF"), state="AC")`
`table(tab$NOME_UF)`

**Comment by Cepesp-Fgv** [comment]
Corrigido.
