### ISSUE TITLE
Erro na informação da página inicial

### ISSUE THREAD

**Issue by marcofaga** [Cepesp-Fgv/cepesp-r#64]
Olá, na página ininicial de vocês no GitHub está descrita uma informação incorreta. Na tabela, o ano de 1998 aparece como indicando que contém informações para vereador. Mas em 1998 as eleições eram estaduais e federais. Abs

**Comment by lins-morandi** [comment]
Olá, Marco. Acho que a nossa documentação não estava clara. Acabamos de fazer uma atualização na página inicial. A tabela que liga anos a cargos é a seguinte (ver imagem anexa). Obrigada pelo comentário. Abs,
![Screenshot from 2019-04-16 16-20-47](https://user-images.githubusercontent.com/47109522/56237962-b2d76480-6063-11e9-8d3d-307fb4c331c4.png)
