### ISSUE TITLE
Problema no período na consulta Secretários (site e API)

### ISSUE THREAD

**Issue by marinamerlo** [Cepesp-Fgv/cepesp-r#75]
Erro no site e na API quando tentamos filtrar os banco de secretários por período:

sec<-get_secretaries(state="AC", name = NULL,period="2002-2006")
status: RUNNING, elapsed: 1s
status: RUNNING, elapsed: 16s
status: RUNNING, elapsed: 18s
status: CANCELLED, elapsed: 20s
Error in error("The query has failed. Please, check if your parameters are valid.") : 
  could not find function "error"

http://cepespdata.io/consulta/secretarios?government_period=2002-2006&uf_filter=AC&name_filter=&c%5B%5D=NOME_SECRETARIO&c%5B%5D=RG&c%5B%5D=CARGO&c%5B%5D=ORGAO_OCUPADO&c%5B%5D=UF_ORGAO_OCUPADO&c%5B%5D=UF&c%5B%5D=CPF&c%5B%5D=TITULO_DE_ELEITOR&c%5B%5D=DATA_ASSUMIU&c%5B%5D=DATA_DEIXOU&c%5B%5D=DATA_NASCIMENTO

![erro_sec](https://user-images.githubusercontent.com/15651407/60207875-534cc080-982d-11e9-89c2-0f82e2c38e50.PNG)

**Comment by Cepesp-Fgv** [comment]
Enviamos uma correção para o servidor de teste. Assim que aprovada, esta correção irá para o servidor de produção.
![Captura de Tela 2019-06-26 às 20 28 52](https://user-images.githubusercontent.com/28055677/60221880-b3edf480-9851-11e9-8baf-268595514df9.png)
