### ISSUE TITLE
Erro ao extrair os dados para Município e Zona Eleitoral

### ISSUE THREAD

**Issue by lcgodoy** [Cepesp-Fgv/cepesp-r#8]
Quando tentei fazer a seguinte consulta:  
`data <- votes(year = 2014, regional_aggregation = 7, political_aggregation = 1, position = 1)`  

O seguinte erro foi reportado:
`Parsed with column specification:
cols(
  `Usecols do not match names.` = col_character()
)`

Ainda existem consultas desabilitadas ?

**Comment by luizgabriel** [comment]
Fixed.
